@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox

actor "HRM" as HRM
participant ":RegisterJobUI" as UI
participant ":RegisterJobController" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as REPS
participant ":JobRepository" as jobRepository

activate HRM

    HRM -> UI : asks to register a new job
    activate UI

        UI -> CTRL** : create

    UI --> HRM : requests data
    deactivate UI

    HRM -> UI : types/selects requested data
    activate UI

    UI --> HRM : shows all data and requests confirmation
    deactivate UI

    HRM -> UI : confirms data
    activate UI

        UI -> CTRL: registerJob(name, description)
        activate CTRL

            CTRL -> REP: getInstance()
            activate REP

            REP --> CTRL: repositories
            deactivate REP

            CTRL -> REPS: getJobRepository()
            activate REPS

            REPS --> CTRL: jobRepository
            deactivate REPS

            CTRL -> jobRepository: registerJob(name, description)
            activate jobRepository

                ref over jobRepository
                    Register Job
                end ref

            jobRepository --> CTRL: job
            deactivate jobRepository

        CTRL --> UI: job
        deactivate CTRL

    UI --> HRM : displays operation success
    deactivate UI

deactivate HRM

@enduml