@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Initiates a team proposal generation
    activate System

        System --> Employee : Requests data (min and max team size)
    deactivate System

    Employee -> System : Types requested data
    activate System

        System --> Employee : Requests to choose a skill
    deactivate System

    Employee -> System : Chooses skill
    activate System

        System --> Employee : Generate team proposal and requests for confirmation
    deactivate System

    Employee -> System : Confirms the team generated
    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml