@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Vehicle and Equipment \nFleet Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : ask to list vehicles needing check-up
    activate System

        System -> Employee : shows the list of vehicles that require check-up

    System --> Employee : displays operation success

    deactivate System

@enduml