@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber
'hide footbox
participant ":AssignSkillControlller" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as REPS
participant "collaboratorsRepository:\nCollaboratorsRepository" as collaboratorsRepository
autonumber 2
 -> CTRL : getCollaboratorsList()
autonumber 2.1
activate CTRL
    group Get Collaborator Object
            CTRL -> REP : getInstance()
            activate REP
            REP --> CTRL: repositories
            deactivate REP
            CTRL -> REPS : getCollaboratorsRepository()
            activate REPS
            REPS --> CTRL: CollaboratorsRepository
            deactivate REPS
            CTRL -> collaboratorsRepository: getCollabboratorList()
            activate collaboratorsRepository
            collaboratorsRepository --> CTRL : CollaboratorList
            deactivate collaboratorsRepository
    end
    autonumber 3
    <-- CTRL  : CollaboratorList
deactivate CTRL
@enduml