@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber
'hide footbox
participant ":AssignSkillControlller" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as REPS
participant "collaboratorsRepository:\nCollaboratorsRepository" as collaboratorsRepository
autonumber 13
 -> CTRL : getCollaboratorByName (collaboratorName)
autonumber 13.1
activate CTRL
    group Get Collaborator Object
            CTRL -> REP : getInstance()
            activate REP
            REP --> CTRL: repositories
            deactivate REP
            CTRL -> REPS : getCollaboratorByName (collaboratorName)
            activate REPS
            REPS --> CTRL: collaboratorsRepository
            deactivate REPS
            CTRL -> collaboratorsRepository: getCollaboratorList()
            activate collaboratorsRepository
            collaboratorsRepository --> CTRL : collaborator
            deactivate collaboratorsRepository
    end
    autonumber 14
    <-- CTRL  : collaborator
deactivate CTRL
@enduml