@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber
'hide footbox
participant ":AssignSkillControlller" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as REPS
participant "skillsRepository:\nSkillsRepository" as skillsRepository
autonumber 6
 -> CTRL : getSkillsList()
autonumber 6.1
activate CTRL
    group Get Skills List
            CTRL -> REP : getInstance()
            activate REP
            REP --> CTRL: repositories
            deactivate REP
            CTRL -> REPS : getSkillsRepository()
            activate REPS
            REPS --> CTRL: SkillsRepository
            deactivate REPS
            CTRL -> skillsRepository: getSkillList()
            activate skillsRepository
            skillsRepository --> CTRL : SkillsList
            deactivate skillsRepository
    end
    autonumber 7
    <-- CTRL  : SkillsList
deactivate CTRL
@enduml